apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- rbac.yaml

configMapGenerator:
- name: ssh-keys
  files:
  - authorized_keys=authorized_keys