---
# Namespace-level read role with pod exec exception
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader-with-exec
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/attach", "pods/portforward", "pods/log"]
  verbs: ["create", "get"]
---
# Cluster-level read role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# Bind the namespace reader role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-namespace-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-reader-with-exec
subjects:
- kind: ServiceAccount
  name: ssh-admin
  namespace: default
---
# Bind the cluster reader role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssh-admin-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: ssh-admin
  namespace: default