apiVersion: v1
kind: Service
metadata:
  name: ssh-login
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ssh-login.internal.example.com
    external-dns.alpha.kubernetes.io/internal: "true"
spec:
  selector:
    app: ssh-login
  ports:
  - port: 22
    targetPort: 2222
    name: ssh
  type: LoadBalancer